import Head from "next/head";

export const HeadComponent = ({ children }) => {
  return (
    <Head>
      <title>{children}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
